def pathName = "EG.One.DotNetCoreTemplate";

node { 
    def buildDetails = checkoutWithDetails(buildNumber:env.BUILD_NUMBER)
    
    stage('Build') {
        sh "dotnet restore --configfile=Nuget.Config"
        sh "dotnet publish -c Release"
    }
    
    stage('Unit tests') {
        sh "dotnet restore test/${pathName}.UnitTest"
        sh "dotnet test test/${pathName}.UnitTest/${pathName}.UnitTest.csproj"
    }

    if (env.BRANCH_NAME == "master") {
        buildDockerImage(buildDetails)
    }
    
}
