def pathName = "EG.One.DotNetCoreTemplate";

node { 
    def buildDetails = checkoutWithDetails(buildNumber:env.BUILD_NUMBER, branch: env.BRANCH_NAME)
    
    stage('Build') {
        sh "dotnet restore --configfile=Nuget.Config"
        sh "dotnet publish -c Release"
    }
    
    stage('Unit tests') {
        sh "dotnet restore test/${pathName}.UnitTest"
        sh "dotnet test test/${pathName}.UnitTest/${pathName}.UnitTest.csproj"
    }

    buildDockerImage(buildDetails)
    
}
